Repository parpeoficial/stackerjs, pull requests merged in 2018-06, with the labels that each got.

#62 fix(package): update dependencies
  .babelrc
  package-lock.json
  package.json
  src/commands/CreateCommandCommand.js
  test/Functional/Forklift.test.js
  yarn.lock
Labels: enhancement

#63 fix(package): update dependencies
  package-lock.json
  package.json
  src/lib/MicroService.js
  yarn.lock
Labels: enhancement

#64 fix(DB): how database connection is handled
  src/lib/Forklift.js
  src/lib/MicroService.js
  src/lib/index.js
  test/Functional/Forklift.test.js
Labels: bug

#65 fix(DB): don't close database connection on end
  .babelrc
  src/lib/MicroService.js
Labels: bug, enhancement

#66 fix(package): update dependencies
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#67 fix(package): update dependencies
  package-lock.json
  package.json
  yarn.lock
Labels: bug, enhancement

#68 fix(package): update dependencies
  .travis.yml
  package.json
  yarn.lock
Labels: bug

#69 fix(package): update dependencies
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#70 Code quality
  .eslintrc.json
  package-lock.json
  package.json
  src/lib/Forklift.js
  yarn.lock
Labels: bug, enhancement
